
 Network ricassiocosta-python_backend  Creating
 Network ricassiocosta-python_backend  Created
 Container ricassiocosta-python-redis-1  Creating
 Container ricassiocosta-python-redis-1  Created
 Container ricassiocosta-python-worker-heavy-1  Creating
 Container ricassiocosta-python-backend-api-1-1  Creating
 Container ricassiocosta-python-worker-light-1  Creating
 Container ricassiocosta-python-backend-api-2-1  Creating
 Container ricassiocosta-python-health-check-1  Creating
 Container ricassiocosta-python-worker-light-1  Created
 Container ricassiocosta-python-backend-api-1-1  Created
 Container ricassiocosta-python-worker-heavy-1  Created
 Container ricassiocosta-python-backend-api-2-1  Created
 Container ricassiocosta-python-nginx-1  Creating
 Container ricassiocosta-python-health-check-1  Created
 Container ricassiocosta-python-nginx-1  Created
Attaching to backend-api-1-1, backend-api-2-1, health-check-1, nginx-1, redis-1, worker-heavy-1, worker-light-1
redis-1          | 1:C 14 Jul 2025 22:59:13.531 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis-1          | 1:C 14 Jul 2025 22:59:13.531 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis-1          | 1:C 14 Jul 2025 22:59:13.531 * Redis version=7.4.5, bits=64, commit=00000000, modified=0, pid=1, just started
redis-1          | 1:C 14 Jul 2025 22:59:13.531 * Configuration loaded
redis-1          | 1:M 14 Jul 2025 22:59:13.532 * monotonic clock: POSIX clock_gettime
redis-1          | 1:M 14 Jul 2025 22:59:13.532 * Running mode=standalone, port=6379.
redis-1          | 1:M 14 Jul 2025 22:59:13.581 * Server initialized
redis-1          | 1:M 14 Jul 2025 22:59:13.582 * Ready to accept connections tcp
nginx-1          | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1          | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1          | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1          | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1          | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1          | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1          | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1          | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1          | /docker-entrypoint.sh: Configuration complete; ready for start up
worker-heavy-1   | Worker started.
nginx-1          | 2025/07/14 22:59:16 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://172.19.0.8:9999/payments-summary", host: "localhost:9999"
nginx-1          | 2025/07/14 22:59:16 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://172.19.0.5:9999/payments-summary", host: "localhost:9999"
nginx-1          | 172.19.0.1 - - [14/Jul/2025:22:59:16 +0000] "GET /payments-summary HTTP/1.1" 502 157 "-" "curl/7.88.1"
worker-light-1   | Worker started.
nginx-1          | 2025/07/14 22:59:21 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://172.19.0.8:9999/payments-summary", host: "localhost:9999"
nginx-1          | 2025/07/14 22:59:21 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: , request: "GET /payments-summary HTTP/1.1", upstream: "http://172.19.0.5:9999/payments-summary", host: "localhost:9999"
nginx-1          | 172.19.0.1 - - [14/Jul/2025:22:59:21 +0000] "GET /payments-summary HTTP/1.1" 502 157 "-" "curl/7.88.1"
backend-api-2-1  | INFO:     Started server process [1]
backend-api-2-1  | INFO:     Waiting for application startup.
backend-api-2-1  | INFO:     Application startup complete.
backend-api-2-1  | INFO:     Uvicorn running on http://0.0.0.0:9999 (Press CTRL+C to quit)
backend-api-1-1  | INFO:     Started server process [1]
backend-api-1-1  | INFO:     Waiting for application startup.
backend-api-1-1  | INFO:     Application startup complete.
backend-api-1-1  | INFO:     Uvicorn running on http://0.0.0.0:9999 (Press CTRL+C to quit)
backend-api-1-1  | INFO:     172.19.0.9:35134 - "GET /payments-summary HTTP/1.1" 500 Internal Server Error
backend-api-1-1  | ERROR:    Exception in ASGI application
backend-api-1-1  | Traceback (most recent call last):
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
backend-api-1-1  |     result = await app(  # type: ignore[func-returns-value]
backend-api-1-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
backend-api-1-1  |     return await self.app(scope, receive, send)
backend-api-1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
backend-api-1-1  |     await super().__call__(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 112, in __call__
backend-api-1-1  |     await self.middleware_stack(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
backend-api-1-1  |     raise exc
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
backend-api-1-1  |     await self.app(scope, receive, _send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
backend-api-1-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend-api-1-1  |     raise exc
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
backend-api-1-1  |     await app(scope, receive, sender)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 714, in __call__
backend-api-1-1  |     await self.middleware_stack(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 734, in app
backend-api-1-1  |     await route.handle(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
backend-api-1-1  |     await self.app(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
backend-api-1-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
nginx-1          | 172.19.0.1 - - [14/Jul/2025:22:59:26 +0000] "GET /payments-summary HTTP/1.1" 500 21 "-" "curl/7.88.1"
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend-api-1-1  |     raise exc
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
backend-api-1-1  |     await app(scope, receive, sender)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
backend-api-1-1  |     response = await f(request)
backend-api-1-1  |                ^^^^^^^^^^^^^^^^
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
backend-api-1-1  |     raw_response = await run_endpoint_function(
backend-api-1-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
backend-api-1-1  |     return await dependant.call(**values)
backend-api-1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-1-1  |   File "/app/app/main.py", line 18, in payments_summary
backend-api-1-1  |     return await get_summary(datetime.fromisoformat(from_), datetime.fromisoformat(to))
backend-api-1-1  |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-1-1  | TypeError: fromisoformat: argument must be str
health-check-1   | Health check service started.
health-check-1   | Checking health of http://payment-processor-default:8080 at 2025-07-14 22:59:26.994947
health-check-1   | Checking health of http://payment-processor-fallback:8080 at 2025-07-14 22:59:27.244710
backend-api-1-1  | INFO:     172.19.0.9:60444 - "GET /payments-summary HTTP/1.1" 500 Internal Server Error
backend-api-1-1  | ERROR:    Exception in ASGI application
backend-api-1-1  | Traceback (most recent call last):
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
backend-api-1-1  |     result = await app(  # type: ignore[func-returns-value]
backend-api-1-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
backend-api-1-1  |     return await self.app(scope, receive, send)
backend-api-1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
backend-api-1-1  |     await super().__call__(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 112, in __call__
backend-api-1-1  |     await self.middleware_stack(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
backend-api-1-1  |     raise exc
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
backend-api-1-1  |     await self.app(scope, receive, _send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
backend-api-1-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend-api-1-1  |     raise exc
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
backend-api-1-1  |     await app(scope, receive, sender)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 714, in __call__
backend-api-1-1  |     await self.middleware_stack(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 734, in app
backend-api-1-1  |     await route.handle(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
backend-api-1-1  |     await self.app(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
backend-api-1-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
nginx-1          | 172.19.0.1 - - [14/Jul/2025:22:59:31 +0000] "GET /payments-summary HTTP/1.1" 500 21 "-" "curl/7.88.1"
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend-api-1-1  |     raise exc
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
backend-api-1-1  |     await app(scope, receive, sender)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
backend-api-1-1  |     response = await f(request)
backend-api-1-1  |                ^^^^^^^^^^^^^^^^
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
backend-api-1-1  |     raw_response = await run_endpoint_function(
backend-api-1-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
backend-api-1-1  |     return await dependant.call(**values)
backend-api-1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-1-1  |   File "/app/app/main.py", line 18, in payments_summary
backend-api-1-1  |     return await get_summary(datetime.fromisoformat(from_), datetime.fromisoformat(to))
backend-api-1-1  |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-1-1  | TypeError: fromisoformat: argument must be str
health-check-1   | Checking health of http://payment-processor-default:8080 at 2025-07-14 22:59:32.401336
health-check-1   | Checking health of http://payment-processor-fallback:8080 at 2025-07-14 22:59:32.405537
backend-api-2-1  | INFO:     172.19.0.9:38122 - "GET /payments-summary HTTP/1.1" 500 Internal Server Error
backend-api-2-1  | ERROR:    Exception in ASGI application
nginx-1          | 172.19.0.1 - - [14/Jul/2025:22:59:36 +0000] "GET /payments-summary HTTP/1.1" 500 21 "-" "curl/7.88.1"
backend-api-2-1  | Traceback (most recent call last):
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
backend-api-2-1  |     result = await app(  # type: ignore[func-returns-value]
backend-api-2-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
backend-api-2-1  |     return await self.app(scope, receive, send)
backend-api-2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
backend-api-2-1  |     await super().__call__(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 112, in __call__
backend-api-2-1  |     await self.middleware_stack(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
backend-api-2-1  |     raise exc
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
backend-api-2-1  |     await self.app(scope, receive, _send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
backend-api-2-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend-api-2-1  |     raise exc
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
backend-api-2-1  |     await app(scope, receive, sender)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 714, in __call__
backend-api-2-1  |     await self.middleware_stack(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 734, in app
backend-api-2-1  |     await route.handle(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
backend-api-2-1  |     await self.app(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
backend-api-2-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend-api-2-1  |     raise exc
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
backend-api-2-1  |     await app(scope, receive, sender)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
backend-api-2-1  |     response = await f(request)
backend-api-2-1  |                ^^^^^^^^^^^^^^^^
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
backend-api-2-1  |     raw_response = await run_endpoint_function(
backend-api-2-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
backend-api-2-1  |     return await dependant.call(**values)
backend-api-2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-2-1  |   File "/app/app/main.py", line 18, in payments_summary
backend-api-2-1  |     return await get_summary(datetime.fromisoformat(from_), datetime.fromisoformat(to))
backend-api-2-1  |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-2-1  | TypeError: fromisoformat: argument must be str
health-check-1   | Checking health of http://payment-processor-default:8080 at 2025-07-14 22:59:37.446437
health-check-1   | Checking health of http://payment-processor-fallback:8080 at 2025-07-14 22:59:37.449243
backend-api-2-1  | INFO:     172.19.0.9:43186 - "GET /payments-summary HTTP/1.1" 500 Internal Server Error
backend-api-2-1  | ERROR:    Exception in ASGI application
nginx-1          | 172.19.0.1 - - [14/Jul/2025:22:59:41 +0000] "GET /payments-summary HTTP/1.1" 500 21 "-" "curl/7.88.1"
backend-api-2-1  | Traceback (most recent call last):
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
backend-api-2-1  |     result = await app(  # type: ignore[func-returns-value]
backend-api-2-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
backend-api-2-1  |     return await self.app(scope, receive, send)
backend-api-2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
backend-api-2-1  |     await super().__call__(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 112, in __call__
backend-api-2-1  |     await self.middleware_stack(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
backend-api-2-1  |     raise exc
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
backend-api-2-1  |     await self.app(scope, receive, _send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
backend-api-2-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend-api-2-1  |     raise exc
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
backend-api-2-1  |     await app(scope, receive, sender)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 714, in __call__
backend-api-2-1  |     await self.middleware_stack(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 734, in app
backend-api-2-1  |     await route.handle(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
backend-api-2-1  |     await self.app(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
backend-api-2-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend-api-2-1  |     raise exc
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
backend-api-2-1  |     await app(scope, receive, sender)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
backend-api-2-1  |     response = await f(request)
backend-api-2-1  |                ^^^^^^^^^^^^^^^^
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
backend-api-2-1  |     raw_response = await run_endpoint_function(
backend-api-2-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
backend-api-2-1  |     return await dependant.call(**values)
backend-api-2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-2-1  |   File "/app/app/main.py", line 18, in payments_summary
backend-api-2-1  |     return await get_summary(datetime.fromisoformat(from_), datetime.fromisoformat(to))
backend-api-2-1  |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-2-1  | TypeError: fromisoformat: argument must be str
health-check-1   | Checking health of http://payment-processor-default:8080 at 2025-07-14 22:59:42.452691
health-check-1   | Checking health of http://payment-processor-fallback:8080 at 2025-07-14 22:59:42.473594
backend-api-1-1  | INFO:     172.19.0.9:39780 - "GET /payments-summary HTTP/1.1" 500 Internal Server Error
backend-api-1-1  | ERROR:    Exception in ASGI application
backend-api-1-1  | Traceback (most recent call last):
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
backend-api-1-1  |     result = await app(  # type: ignore[func-returns-value]
backend-api-1-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
backend-api-1-1  |     return await self.app(scope, receive, send)
backend-api-1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
backend-api-1-1  |     await super().__call__(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 112, in __call__
backend-api-1-1  |     await self.middleware_stack(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
backend-api-1-1  |     raise exc
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
backend-api-1-1  |     await self.app(scope, receive, _send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
backend-api-1-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend-api-1-1  |     raise exc
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
backend-api-1-1  |     await app(scope, receive, sender)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 714, in __call__
backend-api-1-1  |     await self.middleware_stack(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 734, in app
backend-api-1-1  |     await route.handle(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
backend-api-1-1  |     await self.app(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
backend-api-1-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend-api-1-1  |     raise exc
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
backend-api-1-1  |     await app(scope, receive, sender)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
backend-api-1-1  |     response = await f(request)
backend-api-1-1  |                ^^^^^^^^^^^^^^^^
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
backend-api-1-1  |     raw_response = await run_endpoint_function(
backend-api-1-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
backend-api-1-1  |     return await dependant.call(**values)
backend-api-1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-1-1  |   File "/app/app/main.py", line 18, in payments_summary
backend-api-1-1  |     return await get_summary(datetime.fromisoformat(from_), datetime.fromisoformat(to))
backend-api-1-1  |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-1-1  | TypeError: fromisoformat: argument must be str
nginx-1          | 172.19.0.1 - - [14/Jul/2025:22:59:46 +0000] "GET /payments-summary HTTP/1.1" 500 21 "-" "curl/7.88.1"
health-check-1   | Checking health of http://payment-processor-default:8080 at 2025-07-14 22:59:47.544904
health-check-1   | Checking health of http://payment-processor-fallback:8080 at 2025-07-14 22:59:47.547410
backend-api-2-1  | INFO:     172.19.0.9:33036 - "GET /payments-summary HTTP/1.1" 500 Internal Server Error
backend-api-2-1  | ERROR:    Exception in ASGI application
backend-api-2-1  | Traceback (most recent call last):
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
backend-api-2-1  |     result = await app(  # type: ignore[func-returns-value]
backend-api-2-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
backend-api-2-1  |     return await self.app(scope, receive, send)
backend-api-2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
backend-api-2-1  |     await super().__call__(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 112, in __call__
backend-api-2-1  |     await self.middleware_stack(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
backend-api-2-1  |     raise exc
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
backend-api-2-1  |     await self.app(scope, receive, _send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
backend-api-2-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend-api-2-1  |     raise exc
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
backend-api-2-1  |     await app(scope, receive, sender)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 714, in __call__
backend-api-2-1  |     await self.middleware_stack(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 734, in app
backend-api-2-1  |     await route.handle(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
backend-api-2-1  |     await self.app(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
backend-api-2-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend-api-2-1  |     raise exc
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
backend-api-2-1  |     await app(scope, receive, sender)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
backend-api-2-1  |     response = await f(request)
backend-api-2-1  |                ^^^^^^^^^^^^^^^^
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
backend-api-2-1  |     raw_response = await run_endpoint_function(
backend-api-2-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
backend-api-2-1  |     return await dependant.call(**values)
backend-api-2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-2-1  |   File "/app/app/main.py", line 18, in payments_summary
backend-api-2-1  |     return await get_summary(datetime.fromisoformat(from_), datetime.fromisoformat(to))
backend-api-2-1  |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-2-1  | TypeError: fromisoformat: argument must be str
nginx-1          | 172.19.0.1 - - [14/Jul/2025:22:59:51 +0000] "GET /payments-summary HTTP/1.1" 500 21 "-" "curl/7.88.1"
health-check-1   | Checking health of http://payment-processor-default:8080 at 2025-07-14 22:59:52.550515
health-check-1   | Checking health of http://payment-processor-fallback:8080 at 2025-07-14 22:59:52.553529
backend-api-1-1  | INFO:     172.19.0.9:38506 - "GET /payments-summary HTTP/1.1" 500 Internal Server Error
backend-api-1-1  | ERROR:    Exception in ASGI application
nginx-1          | 172.19.0.1 - - [14/Jul/2025:22:59:56 +0000] "GET /payments-summary HTTP/1.1" 500 21 "-" "curl/7.88.1"
backend-api-1-1  | Traceback (most recent call last):
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
backend-api-1-1  |     result = await app(  # type: ignore[func-returns-value]
backend-api-1-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
backend-api-1-1  |     return await self.app(scope, receive, send)
backend-api-1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
backend-api-1-1  |     await super().__call__(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 112, in __call__
backend-api-1-1  |     await self.middleware_stack(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
backend-api-1-1  |     raise exc
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
backend-api-1-1  |     await self.app(scope, receive, _send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
backend-api-1-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend-api-1-1  |     raise exc
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
backend-api-1-1  |     await app(scope, receive, sender)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 714, in __call__
backend-api-1-1  |     await self.middleware_stack(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 734, in app
backend-api-1-1  |     await route.handle(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
backend-api-1-1  |     await self.app(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
backend-api-1-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend-api-1-1  |     raise exc
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
backend-api-1-1  |     await app(scope, receive, sender)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
backend-api-1-1  |     response = await f(request)
backend-api-1-1  |                ^^^^^^^^^^^^^^^^
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
backend-api-1-1  |     raw_response = await run_endpoint_function(
backend-api-1-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
backend-api-1-1  |     return await dependant.call(**values)
backend-api-1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-1-1  |   File "/app/app/main.py", line 18, in payments_summary
backend-api-1-1  |     return await get_summary(datetime.fromisoformat(from_), datetime.fromisoformat(to))
backend-api-1-1  |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-1-1  | TypeError: fromisoformat: argument must be str
health-check-1   | Checking health of http://payment-processor-default:8080 at 2025-07-14 22:59:57.645420
health-check-1   | Checking health of http://payment-processor-fallback:8080 at 2025-07-14 22:59:57.648599
backend-api-2-1  | INFO:     172.19.0.9:45272 - "GET /payments-summary HTTP/1.1" 500 Internal Server Error
backend-api-2-1  | ERROR:    Exception in ASGI application
nginx-1          | 172.19.0.1 - - [14/Jul/2025:23:00:01 +0000] "GET /payments-summary HTTP/1.1" 500 21 "-" "curl/7.88.1"
backend-api-2-1  | Traceback (most recent call last):
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
backend-api-2-1  |     result = await app(  # type: ignore[func-returns-value]
backend-api-2-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
backend-api-2-1  |     return await self.app(scope, receive, send)
backend-api-2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
backend-api-2-1  |     await super().__call__(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 112, in __call__
backend-api-2-1  |     await self.middleware_stack(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
backend-api-2-1  |     raise exc
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
backend-api-2-1  |     await self.app(scope, receive, _send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
backend-api-2-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend-api-2-1  |     raise exc
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
backend-api-2-1  |     await app(scope, receive, sender)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 714, in __call__
backend-api-2-1  |     await self.middleware_stack(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 734, in app
backend-api-2-1  |     await route.handle(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
backend-api-2-1  |     await self.app(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
backend-api-2-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend-api-2-1  |     raise exc
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
backend-api-2-1  |     await app(scope, receive, sender)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
backend-api-2-1  |     response = await f(request)
backend-api-2-1  |                ^^^^^^^^^^^^^^^^
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
backend-api-2-1  |     raw_response = await run_endpoint_function(
backend-api-2-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
backend-api-2-1  |     return await dependant.call(**values)
backend-api-2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-2-1  |   File "/app/app/main.py", line 18, in payments_summary
backend-api-2-1  |     return await get_summary(datetime.fromisoformat(from_), datetime.fromisoformat(to))
backend-api-2-1  |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-2-1  | TypeError: fromisoformat: argument must be str
health-check-1   | Checking health of http://payment-processor-default:8080 at 2025-07-14 23:00:02.743888
health-check-1   | Checking health of http://payment-processor-fallback:8080 at 2025-07-14 23:00:02.747290
backend-api-1-1  | INFO:     172.19.0.9:48238 - "GET /payments-summary HTTP/1.1" 500 Internal Server Error
backend-api-1-1  | ERROR:    Exception in ASGI application
backend-api-1-1  | Traceback (most recent call last):
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
backend-api-1-1  |     result = await app(  # type: ignore[func-returns-value]
backend-api-1-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
backend-api-1-1  |     return await self.app(scope, receive, send)
backend-api-1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
backend-api-1-1  |     await super().__call__(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 112, in __call__
backend-api-1-1  |     await self.middleware_stack(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
backend-api-1-1  |     raise exc
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
backend-api-1-1  |     await self.app(scope, receive, _send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
backend-api-1-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend-api-1-1  |     raise exc
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
backend-api-1-1  |     await app(scope, receive, sender)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 714, in __call__
backend-api-1-1  |     await self.middleware_stack(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 734, in app
backend-api-1-1  |     await route.handle(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
backend-api-1-1  |     await self.app(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
backend-api-1-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend-api-1-1  |     raise exc
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
backend-api-1-1  |     await app(scope, receive, sender)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
backend-api-1-1  |     response = await f(request)
nginx-1          | 172.19.0.1 - - [14/Jul/2025:23:00:06 +0000] "GET /payments-summary HTTP/1.1" 500 21 "-" "curl/7.88.1"
backend-api-1-1  |                ^^^^^^^^^^^^^^^^
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
backend-api-1-1  |     raw_response = await run_endpoint_function(
backend-api-1-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
backend-api-1-1  |     return await dependant.call(**values)
backend-api-1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-1-1  |   File "/app/app/main.py", line 18, in payments_summary
backend-api-1-1  |     return await get_summary(datetime.fromisoformat(from_), datetime.fromisoformat(to))
backend-api-1-1  |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-1-1  | TypeError: fromisoformat: argument must be str
health-check-1   | Checking health of http://payment-processor-default:8080 at 2025-07-14 23:00:07.753333
health-check-1   | Checking health of http://payment-processor-fallback:8080 at 2025-07-14 23:00:07.773071
backend-api-2-1  | INFO:     172.19.0.9:57932 - "GET /payments-summary HTTP/1.1" 500 Internal Server Error
backend-api-2-1  | ERROR:    Exception in ASGI application
nginx-1          | 172.19.0.1 - - [14/Jul/2025:23:00:11 +0000] "GET /payments-summary HTTP/1.1" 500 21 "-" "curl/7.88.1"
backend-api-2-1  | Traceback (most recent call last):
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
backend-api-2-1  |     result = await app(  # type: ignore[func-returns-value]
backend-api-2-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
backend-api-2-1  |     return await self.app(scope, receive, send)
backend-api-2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
backend-api-2-1  |     await super().__call__(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 112, in __call__
backend-api-2-1  |     await self.middleware_stack(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
backend-api-2-1  |     raise exc
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
backend-api-2-1  |     await self.app(scope, receive, _send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
backend-api-2-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend-api-2-1  |     raise exc
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
backend-api-2-1  |     await app(scope, receive, sender)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 714, in __call__
backend-api-2-1  |     await self.middleware_stack(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 734, in app
backend-api-2-1  |     await route.handle(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
backend-api-2-1  |     await self.app(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
backend-api-2-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend-api-2-1  |     raise exc
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
backend-api-2-1  |     await app(scope, receive, sender)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
backend-api-2-1  |     response = await f(request)
backend-api-2-1  |                ^^^^^^^^^^^^^^^^
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
backend-api-2-1  |     raw_response = await run_endpoint_function(
backend-api-2-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
backend-api-2-1  |     return await dependant.call(**values)
backend-api-2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-2-1  |   File "/app/app/main.py", line 18, in payments_summary
backend-api-2-1  |     return await get_summary(datetime.fromisoformat(from_), datetime.fromisoformat(to))
backend-api-2-1  |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-2-1  | TypeError: fromisoformat: argument must be str
health-check-1   | Checking health of http://payment-processor-default:8080 at 2025-07-14 23:00:12.843797
health-check-1   | Checking health of http://payment-processor-fallback:8080 at 2025-07-14 23:00:12.872130
backend-api-1-1  | INFO:     172.19.0.9:50848 - "GET /payments-summary HTTP/1.1" 500 Internal Server Error
backend-api-1-1  | ERROR:    Exception in ASGI application
nginx-1          | 172.19.0.1 - - [14/Jul/2025:23:00:16 +0000] "GET /payments-summary HTTP/1.1" 500 21 "-" "curl/7.88.1"
backend-api-1-1  | Traceback (most recent call last):
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
backend-api-1-1  |     result = await app(  # type: ignore[func-returns-value]
backend-api-1-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
backend-api-1-1  |     return await self.app(scope, receive, send)
backend-api-1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
backend-api-1-1  |     await super().__call__(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 112, in __call__
backend-api-1-1  |     await self.middleware_stack(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
backend-api-1-1  |     raise exc
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
backend-api-1-1  |     await self.app(scope, receive, _send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
backend-api-1-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend-api-1-1  |     raise exc
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
backend-api-1-1  |     await app(scope, receive, sender)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 714, in __call__
backend-api-1-1  |     await self.middleware_stack(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 734, in app
backend-api-1-1  |     await route.handle(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
backend-api-1-1  |     await self.app(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
backend-api-1-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend-api-1-1  |     raise exc
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
backend-api-1-1  |     await app(scope, receive, sender)
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
backend-api-1-1  |     response = await f(request)
backend-api-1-1  |                ^^^^^^^^^^^^^^^^
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
backend-api-1-1  |     raw_response = await run_endpoint_function(
backend-api-1-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-1-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
backend-api-1-1  |     return await dependant.call(**values)
backend-api-1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-1-1  |   File "/app/app/main.py", line 18, in payments_summary
backend-api-1-1  |     return await get_summary(datetime.fromisoformat(from_), datetime.fromisoformat(to))
backend-api-1-1  |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-1-1  | TypeError: fromisoformat: argument must be str
health-check-1   | Checking health of http://payment-processor-default:8080 at 2025-07-14 23:00:17.874949
health-check-1   | Checking health of http://payment-processor-fallback:8080 at 2025-07-14 23:00:17.877743
backend-api-2-1  | INFO:     172.19.0.9:48878 - "GET /payments-summary HTTP/1.1" 500 Internal Server Error
backend-api-2-1  | ERROR:    Exception in ASGI application
nginx-1          | 172.19.0.1 - - [14/Jul/2025:23:00:22 +0000] "GET /payments-summary HTTP/1.1" 500 21 "-" "curl/7.88.1"
backend-api-2-1  | Traceback (most recent call last):
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
backend-api-2-1  |     result = await app(  # type: ignore[func-returns-value]
backend-api-2-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
backend-api-2-1  |     return await self.app(scope, receive, send)
backend-api-2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
backend-api-2-1  |     await super().__call__(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 112, in __call__
backend-api-2-1  |     await self.middleware_stack(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
backend-api-2-1  |     raise exc
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
backend-api-2-1  |     await self.app(scope, receive, _send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
backend-api-2-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend-api-2-1  |     raise exc
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
backend-api-2-1  |     await app(scope, receive, sender)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 714, in __call__
backend-api-2-1  |     await self.middleware_stack(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 734, in app
backend-api-2-1  |     await route.handle(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
backend-api-2-1  |     await self.app(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
backend-api-2-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend-api-2-1  |     raise exc
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
backend-api-2-1  |     await app(scope, receive, sender)
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
backend-api-2-1  |     response = await f(request)
backend-api-2-1  |                ^^^^^^^^^^^^^^^^
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
backend-api-2-1  |     raw_response = await run_endpoint_function(
backend-api-2-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-2-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
backend-api-2-1  |     return await dependant.call(**values)
backend-api-2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-2-1  |   File "/app/app/main.py", line 18, in payments_summary
backend-api-2-1  |     return await get_summary(datetime.fromisoformat(from_), datetime.fromisoformat(to))
backend-api-2-1  |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-api-2-1  | TypeError: fromisoformat: argument must be str
health-check-1   | Checking health of http://payment-processor-default:8080 at 2025-07-14 23:00:22.880744
health-check-1   | Checking health of http://payment-processor-fallback:8080 at 2025-07-14 23:00:22.972357
[Knginx-1 exited with code 0
health-check-1   | Checking health of http://payment-processor-default:8080 at 2025-07-14 23:00:27.976071
health-check-1   | Checking health of http://payment-processor-fallback:8080 at 2025-07-14 23:00:27.978386
backend-api-1-1  | INFO:     Shutting down
backend-api-2-1  | INFO:     Shutting down
backend-api-1-1  | INFO:     Waiting for application shutdown.
backend-api-2-1  | INFO:     Waiting for application shutdown.
backend-api-2-1  | INFO:     Application shutdown complete.
backend-api-1-1  | INFO:     Application shutdown complete.
backend-api-1-1  | INFO:     Finished server process [1]
backend-api-2-1  | INFO:     Finished server process [1]
[Kbackend-api-1-1 exited with code 0
[Kbackend-api-2-1 exited with code 0
health-check-1   | Checking health of http://payment-processor-default:8080 at 2025-07-14 23:00:32.981354
health-check-1   | Checking health of http://payment-processor-fallback:8080 at 2025-07-14 23:00:33.072475
[Kworker-heavy-1 exited with code 137
[Khealth-check-1 exited with code 137
[Kworker-light-1 exited with code 137
redis-1          | 1:signal-handler (1752534037) Received SIGTERM scheduling shutdown...
redis-1          | 1:M 14 Jul 2025 23:00:38.048 * User requested shutdown...
redis-1          | 1:M 14 Jul 2025 23:00:38.048 # Redis is now ready to exit, bye bye...
[Kredis-1 exited with code 0
